
version: "2"
services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    links:
      - mysql  
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: isteam,
      MYSQL_HOST: localhost
      MYSQL_USER: root
    ports:
      - 3307:3306
    restart: unless-stopped
    